name: Sourcegraph LSIF Uploader
description: Upload LSIF data to a Sourcegraph instance
author: Sourcegraph
branding:
  icon: upload
  color: purple

inputs:
  file:
    description: The LSIF dump file to upload.
    default: dump.lsif
  root:
    description: The root of the LSIF dump
    default: ''
  endpoint:
    description: The URL of the Sourcegraph instance.
    default: https://sourcegraph.com
  github_token:
    description: Either 1. a GitHub access token with `repo` or `public_repo` scope, or 2. a GitHub installation access token (necessary when uploading to Sourcegraph.com, or any Sourcegraph instance with lsifEnforceAuth set to true).
    default: ''
  repo:
    description: The repository name (useful for indexing forks; defaults to the current repository)
    default: ''

runs:
  using: docker
  image: Dockerfile
  env:
    IN: ${{ inputs.file }}
    ROOT: ${{ inputs.root }}
    SRC_ENDPOINT: ${{ inputs.endpoint }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    REPOSITORY_OVERRIDE: ${{ inputs.repo }}
